version: '3.4'

services:

  #  The Application
  app:
    container_name: bridge_ui
    build:
      context: ./
      dockerfile: development/app.dockerfile
    working_dir: /var/www
    volumes:
      - .storage/:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_PORT=3306"
      - "REDIS_HOST=database"

  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8990:80

      # The Database
  database:
    image: postgres:12.1
    container_name: Bridge_db
#      image: postgresql- 12.1
    volumes:
          - ./data/postgres:/var/lib/postgresql/data
    environment:
#          - "PGSQL_DATABASE=superbridge"
          - "DB_USERNAME=postgres"
          - "DB_PASSWORD=postgres"
#          - "PGSQL_ROOT_PASSWORD=Coding1!"
    ports:
          - 8991:3306

        # redis
#    cache:
#  image: redis:3.0-alpine

#  volumes:
#    postgres-data:
#version: '2'
#
#services:
#nginx:
#  build:
#    context: ./nginx
#    args:
#      - PHP_UPSTREAM=php-fpm
#  volumes_from:
#    - volumes_source
#  volumes:
#    - ./logs/nginx/:/var/log/nginx
#  links:
#    - php-fpm
#  ports:
#    - "80:80"
#      - "443:443"
#
#php-fpm:
#  build:
#    context: ./php-fpm
#  volumes_from:
#    - volumes_source
#
#postgres:
#  build: ./postgres
#  volumes_from:
#    - volumes_data
#  environment:
#    POSTGRES_DB: superbridge
#    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: Coding1!
#
#  …more containers
#
#### Laravel Application Code Container ######################
#
#volumes_source:
#  image: tianon/true
#  volumes:
#    - ../base/:/var/www/laravel
#
#### Data Container ################################
#
#volumes_data:
#  image: tianon/true
#  volumes:
#    - ./data/postgres:/var/lib/postgresql/data
#      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
